### PR TITLE
[Working] WebSocket 0-RTT fix

### PR DESCRIPTION
**Pull request by sqwwqw5**
Actual built and tested 0-RTT fix, add /?ed=* to your path while * is the max early-data that can be sent, recommended value 2048.
As for the hostname change, Cloudflare doesn't make sense to me, it's a CDN admin panel while CloudFront could actually be used for content distribution, probably no one uses WebSocket without tls anymore anyway I guess, although I still do, for the -1 RTT.

### CODE REVIEW

**Comment by teddysun** [comment]
This PR has conflicts that must be resolved.

**Comment by sqwwqw5** [comment]
> This PR has conflicts that must be resolved.

Should be fixed now, I don't know how the code changed like that.

**Comment by teddysun** [comment]
Sorry, please delete .github/workflows/go.yml and I will merge it

**Review by sqwwqw5 — COMMENTED** [review]
my bad, I did delete it for the first pull, then I pasted it back to do some builds. :)

**Comment by teddysun** [comment]
Thanks a lot!
Merge it.

**Pull request merged**
